server:
  port: 8383

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: # jdbc url작성
    username: # DB 계정
    password: # DB 암호
  jpa :
    # SQL로그가 나올 때 어떤 DBMS의 문법으로 출력할 것인가?
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      # DDL을 생성할때 전략
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true  # SQL로그를 줄바꿈해서 가독성 좋게 출력
    database: mysql # DBMS 계열 설정
  servlet:
    multipart:
      max-file-size: 3MB    # 1개의 파일의 최대업로드 사이즈
      max-request-size: 20MB # 한 번 요청에 들어올 최대 업로드 사이즈

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    com.study.todoapi: debug

jwt:
  secret: DJCzS5O/xxXf5N7YaD1usoUC8WnK6w17g+6TYvj13PW/r3oeHGowXxS0Z13f9ZuAFZelkEAlI6Gvl2FnBbao3Q==

upload:
  path: /Users/yongseopkim/Desktop/spring_prj/upload


# s3 setting
aws:
  credentials:
    accessKey: AKIAU6GD2TO4M6DETLZE
    secretKey: 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
  region: ap-northeast-2
  bucketName: spring-todo-api-file-bucket5157